apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - port: 4000
      targetPort: 4000
      protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  selector:
    app: bank-client
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
